# Лабараторная работа №2
## Работа с библиотеками NumPy, pandas
* Документация [NumPy] <A Href="https://numpy.org/doc/">Прочитать -></A>
* Документация [Pandas] <A Href="https://pandas.pydata.org/docs/index.html">Прочитать -></A>

<img src='https://miro.medium.com/v2/resize:fit:1200/1*Rx0tab3XiwFQfuKgFuSlLA.png' width='500'>

<h3 style="margin-bottom: 0;">Задание №1. Библиотека NumPy</h3>
<h3 style="margin-top: 0;">1.Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5:</h3


In [19]:
import numpy as np
my_array = np.arange(0, 101, 5)
my_array

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

<h3 style="margin-top: 0;">2.Из полученного массива получить массив с кратными 10 числами</h3>


In [28]:
# Фильтруем массив, чтобы оставить только числа, кратные 10
my_array_multiple_of_10 = my_array[my_array % 10 == 0]

print(my_array_multiple_of_10)

[  0  10  20  30  40  50  60  70  80  90 100]


<h3 style="margin-top: 0;">3.Получить двумерный массив с двумя столбцами</h3>

In [43]:
import numpy as np
my_array = np.arange(0, 100, 5)

my_array_multiple_of_10 = my_array[my_array % 10 == 0]

my_array_2d = my_array_multiple_of_10.reshape(-1, 2)

print(my_array_2d)

[[ 0 10]
 [20 30]
 [40 50]
 [60 70]
 [80 90]]


<h3 style="margin-top: 0;">4.Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5</h3>

In [62]:
import numpy as np
my_array = np.arange(0, 100, 5)
my_second_array = my_array - 5
print(my_second_array)

[-5  0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90]


<h3 style="margin-top: 0;">5.Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.</h3>

In [68]:
import numpy as np
my_array = np.arange(0, 100, 5)
my_array_multiple_of_10 = my_array[my_array % 10 == 0]
my_array_2d = my_array_multiple_of_10.reshape(-1, 2)
my_second_array = my_array - 5

combined_array = np.hstack(
    (my_array_2d, my_second_array[:my_array_2d.shape[0]].reshape(-1, 1)))


transposed_array = combined_array.T


print(transposed_array)

[[ 0 20 40 60 80]
 [10 30 50 70 90]
 [-5  0  5 10 15]]


<h3 style="margin-top: 0;">6.Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы</h3>

In [80]:
import numpy as np


my_array = np.arange(0, 100, 5)
my_array_multiple_of_10 = my_array[my_array % 10 == 0]
my_array_2d = my_array_multiple_of_10.reshape(-1, 2)

my_second_array = my_array - 5


my_second_array_trimmed = my_second_array[:my_array_2d.shape[0]]


combined_array = np.hstack(
    (my_array_2d, my_second_array_trimmed.reshape(-1, 1)))


transposed_array = combined_array.T


upper_4_elements = my_array[:4]


second_row = transposed_array[1]
third_row = transposed_array[2]


result_second_row = np.where(
    upper_4_elements != 0, second_row[:4] / upper_4_elements, 0)
result_third_row = np.where(upper_4_elements != 0,
                            third_row[:4] / upper_4_elements, 0)

print("Деление 2-й строки на верхние 4 элемента:", result_second_row)
print("Деление 3-й строки на верхние 4 элемента:", result_third_row)

Деление 2-й строки на верхние 4 элемента: [0.         6.         5.         4.66666667]
Деление 3-й строки на верхние 4 элемента: [0.         0.         0.5        0.66666667]


C:\Users\User\AppData\Local\Temp\ipykernel_6292\1977128867.py:30: RuntimeWarning: divide by zero encountered in divide
  upper_4_elements != 0, second_row[:4] / upper_4_elements, 0)
C:\Users\User\AppData\Local\Temp\ipykernel_6292\1977128867.py:32: RuntimeWarning: divide by zero encountered in divide
  third_row[:4] / upper_4_elements, 0)


<h3 style="margin-top: 0;">7.Оставить только те значения, которые не изменились после деления</h3>

In [92]:
import numpy as np

# Создаем массив с числами до 100, кратными 5
my_array = np.arange(0, 100, 5)

# Фильтруем для получения чисел кратных 10 и преобразуем в двумерный массив
my_array_multiple_of_10 = my_array[my_array % 10 == 0]
my_array_2d = my_array_multiple_of_10.reshape(-1, 2)

# Создаем массив, уменьшая каждый элемент на 5
my_second_array = my_array - 5
my_second_array_trimmed = my_second_array[:my_array_2d.shape[0]]

# Объединяем массивы и транспонируем
combined_array = np.hstack(
    (my_array_2d, my_second_array_trimmed.reshape(-1, 1)))
transposed_array = combined_array.T

# Берем верхние 4 элемента из исходного массива
upper_4_elements = my_array[:4]

# Извлекаем 2-ю и 3-ю строки из транспонированного массива
second_row = transposed_array[1]
third_row = transposed_array[2]

# Выполняем деление с обработкой деления на ноль
result_second_row = np.where(
    upper_4_elements != 0, second_row[:4] / upper_4_elements, 0)
result_third_row = np.where(upper_4_elements != 0,
                            third_row[:4] / upper_4_elements, 0)

# Оставляем только те значения, которые не изменились после деления
unchanged_second_row = second_row[:4][second_row[:4] == result_second_row]
unchanged_third_row = third_row[:4][third_row[:4] == result_third_row]

# Выводим результат
print("Неизмененные значения 2-й строки:", unchanged_second_row)
print("Неизмененные значения 3-й строки:", unchanged_third_row)

Неизмененные значения 2-й строки: []
Неизмененные значения 3-й строки: [0]


C:\Users\User\AppData\Local\Temp\ipykernel_6292\2378011442.py:28: RuntimeWarning: divide by zero encountered in divide
  upper_4_elements != 0, second_row[:4] / upper_4_elements, 0)
C:\Users\User\AppData\Local\Temp\ipykernel_6292\2378011442.py:30: RuntimeWarning: divide by zero encountered in divide
  third_row[:4] / upper_4_elements, 0)


<h3 style="margin-top: 0;">8.Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки</h3>

In [98]:
import numpy as np

# Создаем массив с числами до 100, кратными 5
my_array = np.arange(0, 100, 5)

# Фильтруем для получения чисел кратных 10 и преобразуем в двумерный массив
my_array_multiple_of_10 = my_array[my_array % 10 == 0]
my_array_2d = my_array_multiple_of_10.reshape(-1, 2)

# Создаем массив, уменьшая каждый элемент на 5
my_second_array = my_array - 5
my_second_array_trimmed = my_second_array[:my_array_2d.shape[0]]

# Объединяем массивы и транспонируем
combined_array = np.hstack(
    (my_array_2d, my_second_array_trimmed.reshape(-1, 1)))
transposed_array = combined_array.T

# Для создания трехстрочного двумерного массива
three_row_array = transposed_array[:3]  # Берем только первые три строки

# Меняем местами первую и третью строки
three_row_array[[0, 2]] = three_row_array[[2, 0]]

# Выводим результат
print("Массив после замены первой и третьей строк:")
print(three_row_array)

Массив после замены первой и третьей строк:
[[-5  0  5 10 15]
 [10 30 50 70 90]
 [ 0 20 40 60 80]]


<h3 style="margin-top: 0;">9.Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().</h3>

In [99]:
import numpy as np

# Создаем массив с числами до 100, кратными 5
my_array = np.arange(0, 100, 5)

# Фильтруем для получения чисел кратных 10 и преобразуем в двумерный массив
my_array_multiple_of_10 = my_array[my_array % 10 == 0]
my_array_2d = my_array_multiple_of_10.reshape(-1, 2)

# Создаем массив, уменьшая каждый элемент на 5
my_second_array = my_array - 5
my_second_array_trimmed = my_second_array[:my_array_2d.shape[0]]

# Объединяем массивы и транспонируем
combined_array = np.hstack(
    (my_array_2d, my_second_array_trimmed.reshape(-1, 1)))
transposed_array = combined_array.T

# Получаем трехстрочный массив и меняем местами первую и третью строки
three_row_array = transposed_array[:3]
three_row_array[[0, 2]] = three_row_array[[2, 0]]

# Вычисляем среднее, медиану и стандартное отклонение для каждой строки
means = np.mean(three_row_array, axis=1)
medians = np.median(three_row_array, axis=1)
std_devs = np.std(three_row_array, axis=1)

# Выводим результаты
print("Средние значения для каждой строки:", means)
print("Медианы для каждой строки:", medians)
print("Стандартные отклонения для каждой строки:", std_devs)

Средние значения для каждой строки: [ 5. 50. 40.]
Медианы для каждой строки: [ 5. 50. 40.]
Стандартные отклонения для каждой строки: [ 7.07106781 28.28427125 28.28427125]


<h3 style="margin-top: 0;">10. Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.</h3>

In [100]:
import numpy as np

# Создаем массив с числами до 100, кратными 5
my_array = np.arange(0, 100, 5)

# Фильтруем для получения чисел кратных 10 и преобразуем в двумерный массив
my_array_multiple_of_10 = my_array[my_array % 10 == 0]
my_array_2d = my_array_multiple_of_10.reshape(-1, 2)

# Создаем массив, уменьшая каждый элемент на 5
my_second_array = my_array - 5
my_second_array_trimmed = my_second_array[:my_array_2d.shape[0]]

# Объединяем массивы и транспонируем
combined_array = np.hstack(
    (my_array_2d, my_second_array_trimmed.reshape(-1, 1)))
transposed_array = combined_array.T

# Получаем трехстрочный массив и меняем местами первую и третью строки
three_row_array = transposed_array[:3]
three_row_array[[0, 2]] = three_row_array[[2, 0]]

# Нормализация на максимальное значение вдоль строк
# Получаем максимальные значения
max_values = np.max(three_row_array, axis=1, keepdims=True)
# Делим каждый элемент на максимальное значение
normalized_array = three_row_array / max_values

# Выводим результат
print("Нормализованный массив:")
print(normalized_array)

Нормализованный массив:
[[-0.33333333  0.          0.33333333  0.66666667  1.        ]
 [ 0.11111111  0.33333333  0.55555556  0.77777778  1.        ]
 [ 0.          0.25        0.5         0.75        1.        ]]


<h3 style="margin-bottom: 0;">Задание №2. Библиотека Pandas</h3>
<h3 style="margin-top: 0;">1.Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание данных смотрите ниже.
Изучите полученные данные:
</h3


In [105]:
import pandas as pd
df = pd.read_csv('Global Population Trends(2016-2022).csv')
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

<h3 style="margin-top: 0;">2. Определите размерность данного фрейма (shape())</h3>

In [107]:
df.shape

(1073, 12)

<h3 style="margin-top: 0;">3. Выведите название заголовков столбцов фрейма (columns)</h3>

In [108]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

<h3 style="margin-top: 0;">4. Получите описание всех переменных (полей) (info())</h3>

In [109]:
df.info

<bound method DataFrame.info of           Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Ex

<h3 style="margin-top: 0;">5. Удалите строки, не содержащие значения в столбце «Total Population» - “-” </h3>

In [110]:
df1 = df[df['Total Population'] != '-']
df1

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

<h3 style="margin-top: 0;">6.	Получите описательную статистику по переменным (например, max(), min(), describe())</h3>

In [111]:
df1.describe()

Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000

<h3 style="margin-top: 0;">7. Выполните сортировку данных по нескольким критериям</h3>

In [112]:
df1.loc[:, 'Total Population'] = df1['Total Population'].str.strip()
df1.loc[:, 'Total Population'] = df1['Total Population'].str.replace(',', '')
df1.loc[:, 'Total Population'] = pd.to_numeric(
    df1['Total Population'], errors='coerce')

df_sorted = df1.sort_values(
    by=["Year", "Total Population"], ascending=[True, False])
df_sorted

Country  Year Total Population Urban Population  \
202                      China  2018       1402760000      829,760,595   
432                      India  2018       1369003306      465,871,825   
1019             United States  2018        326838199      268,844,029   
437                  Indonesia  2018        267066843      147,754,731   
725                   Pakistan  2018        219731479       80,566,744   
...                        ...   ...              ...              ...   
907   St. Martin (French Part)  2021            31948                -   
137     British Virgin Islands  2021            31122           15,225   
733                      Palau  2021            18024           14,686   
664                      Nauru  2021            12511           12,511   
997                     Tuvalu  2021            11204            7,259   

     Rural Population Population Density Life Expectancy  Birth Rate  \
202       572,999,405                149            78.0      10.860   
432       903,131,481                460            71.0      17.651   
1019       57,994,170                 36            79.0      11.600   
437       119,312,112                142            70.0      17.179   
725       139,164,735                285            66.0      28.594   
...               ...                ...             ...         ...   
907                 -                  -            80.0      15.053   
137            15,897                  -            74.0       7.634   
733             3,338                  -               -      13.400   
664                 -                  -            64.0      27.560   
997             3,945                  -            65.0      23.484   

      Death Rate Fertility Rate Infant Mortality Rate Growth Rate  
202        7.080          1.554                   6.4         0.0  
432        6.644          2.177                  29.8         1.0  
1019       8.678           1.73                   5.6         1.0  
437        7.496          2.234                  20.8         1.0  
725        6.843          3.685                  57.4         2.0  
...          ...            ...                   ...         ...  
907        4.911          2.415                     -        -2.0  
137        7.613          1.005                   9.9         1.0  
733       10.200            0.0                  15.1         0.0  
664        6.633          3.519                  23.2         2.0  
997       10.159          3.163                  18.1         1.0  

[864 rows x 12 columns]

<h3 style="margin-top: 0;">8. Выведите название страны, которая имеет максимальную численность населения</h3>

In [113]:
df_sorted_byP = df1.sort_values(by="Total Population", ascending=True)
country_max = df_sorted_byP.iloc[-1]["Country"]
country_year = df_sorted_byP.iloc[-1]["Year"]
country_p = df_sorted_byP.iloc[-1]["Total Population"]
print(f'Answer is {country_max} in {country_year} with {country_p} people')

Answer is China in 2021 with 1412360000 people


<h3 style="margin-top: 0;">9. Выведите название страны, которая имеет минимальную численность населения</h3>

In [114]:
country_min = df_sorted_byP.iloc[0]["Country"]
country_year_min = df_sorted_byP.iloc[0]["Year"]
country_m = df_sorted_byP.iloc[0]["Total Population"]
print(f'Answer is {country_min} in {country_year_min} with {country_m} people')

Answer is Tuvalu in 2018 with 10865 people


<h3 style="margin-top: 0;">10. Экспорт фрейма в MS Excel</h3>

In [116]:
df1.to_excel("date_frame.xlsx", index=False, engine='openpyxl')